### ISSUE TITLE
Bot doesn't take water from easiest/nearest source

### ISSUE THREAD

**Issue by TheBlueBurger** [toccatina/altoclef#16] opened 2021-05-23 11:59 UTC
![image](https://user-images.githubusercontent.com/58081413/119259543-07e4ed80-bbcf-11eb-8af5-bd174950f8c7.png)

**Comment by adrisj7** [comment] 2021-05-23 12:03
Yeahh, this is really frustrating. Especially when building a nether portal.

Probably the top "minor bug" on my list to fix right now. Cool to see somebody else found it, so fast too!

**Comment by solonovamax** [comment] 2021-05-24 02:44
that's probably because A* doesn't have any high weights for mining through blocks.
Ideally, it would increase the weight of different blocks based on the following:
- how long it would take to mine through
- how close other water sources are to it

**Comment by adrisj7** [comment] 2021-06-05 18:52
Oops, I made effectively a duplicate of this, (this is now a duplicate of [issue 33](https://github.com/toccatina/altoclef/issues/33)) but I'll reference this issue in that one.

**Closed by adrisj7** 2021-06-05 18:52 UTC
Labels: minor bug
