### ISSUE TITLE
Bot dying a lot to dragon fireballs

### ISSUE THREAD

**Issue by Astatin3** [toccatina/altoclef#88] opened 2021-09-06 02:25 UTC
## Bug Description
Since the splash effect that dragon fireballs create is an entity, the bot does not avoid them

Same for lingering potions

## Steps to Reproduce (as best as you can)

1. dragon fires fireball
2. bot tries to walk through fireball area and dies

## Expected Behavior

bot avoids dragon breath

## Actual Behavior

bot walks straight through dragon breath and dies

**Comment by adrisj7** [comment] 2021-09-06 03:42
Duplicate of https://github.com/toccatina/altoclef/issues/58

**Closed by adrisj7** 2021-09-06 03:42 UTC
Labels: minor bug
